all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client1:
      ansible_host: 3.83.23.62 # Replace with the actual IP address
      ansible_ssh_private_key_file: ~/.ssh/ubuntu_virg.pem # Replace with the actual ssh public key of the client machine